$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  clean:
    command: 'packemon clean'
  build:
    deps:
      - 'clean'
    command:
      - 'packemon'
      - 'build'
      - '--addEngines'
      - '--addExports'
      - '--declaration'
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.*.json'
